### ISSUE TITLE
App close when try to send a GPX by mail

### ISSUE THREAD

**Issue by feliper** [merlos/iOS-Open-GPX-Tracker#24] opened 2016-08-11 20:50 UTC
Using IOS 9.3.4 on an iPhone 6, I record a track, and when I try to send it by email the app close itself ...

**Comment by merlos** [comment] 2016-08-27 11:26
Thanks @feliper, but I cannot reproduce it on my device.
Could you please describe the track. Is it a long track? does it have many points?

Thanks, Juan.

**Comment by merlos** [comment] 2017-02-04 23:28
Closing the issue as no more info was provided and no one else has reported it neither.

**Closed by merlos** 2017-02-04 23:28 UTC
